---

################################################################################
#
# Copyright 2013 Crown copyright (c)
# Land Information New Zealand and the New Zealand Government.
# All rights reserved
#
# This program is released under the terms of the new BSD license. See the
# LICENSE file for more information.
#
################################################################################

- include: base.yml
- include: monitoring.yml

- meta: flush_handlers

  # initial PostgreSQL backup
- include: backup.yml

  # vim: set ts=2 sts=2 sw=2 et:
