---

################################################################################
#
# Copyright 2013 Crown copyright (c)
# Land Information New Zealand and the New Zealand Government.
# All rights reserved
#
# This program is released under the terms of the new BSD license. See the
# LICENSE file for more information.
#
################################################################################

- name: reconfigure timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
  become: yes

- name: service serf-agent restart
  service:
    name: serf-agent
    state: restarted
  become: yes

- name: service cluster-names restart
  service:
    name: cluster-names
    state: restarted
  become: yes

- name: service nagios-nrpe-server restart
  service:
    name: nagios-nrpe-server
    state: restarted
  become: yes

# vim: set ts=8 sts=2 sw=2 et:
