language: python
python:
  - "2.7"
  - "3.5"
  
before-install:
  - postgresql

install:
  #- sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable
  #- sudo apt-get update
  #- sudo apt-get install python-gdal
  #- sudo apt-get install gdal-bin
  
  - sudo apt-get install libgdal-dev libgdal1h
  - pip install --global-option=build_ext --global-option="-I/usr/include/gdal"
  - pip install -r requirements.txt

services:
  - postgresql

before-script:
  - psql -c "create database test_db;" -U postgres
  - psql -c "create user test_user with password 'test_password';" -U postgres
  - psql -c "create extension postgis;" -U postgres

script: 
  - python test/testsuite.py