language: python
python:
  - "2.7"
  - "3.5"
  
before-install:
  - postgresql

install:
  - apt-get install python-gdal
  - pip install -r requirements.txt

services:
  - postgresql

before-script:
  - psql -c "create database test_db;" -U postgres
  - psql -c "create user test_user with password 'test_password';" -U postgres
  - psql -c "create extension postgis;" -U postgres

script: 
  - python test/testsuite.py