language: python
python:
  - "2.7"
  - "3.5"
  
before-install:
  - postgresql

install:
  - pip install --no-install GDAL
  - pip download GDAL
  - python setup.py build_ext --include-dirs=/usr/include/gdal/
  - pip install --no-download GDAL
  - sudo python setup.py install --include-dirs=/usr/include/gdal
  #- sudo apt-get install python-gdal
  - pip install -r requirements.txt

services:
  - postgresql

before-script:
  - psql -c "create database test_db;" -U postgres
  - psql -c "create user test_user with password 'test_password';" -U postgres
  - psql -c "create extension postgis;" -U postgres

script: 
  - python test/testsuite.py