language: python
python:
  - "2.7"
  - "3.5"
  
services:
  - postgresql
  
addons:
  postgresql: "9.1"
    
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y # For postgresql-9.1-postgis-2.1
  - sudo rm -f /etc/apt/sources.list.d/pgdg.list # postgis from pgdg requires different gdal package than the grass package
  - sudo apt-get update -qq
  - sudo apt-get remove postgresql-9.1-postgis-2.1 # Remove postgis from pgdg, will install postgis from ubuntugis-unstable instead
  
install:
  - sudo apt-get install libgdal-dev libgdal1h
  - sudo apt-get install --no-install-recommends postgresql-9.1-postgis-2.1
  - pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`
  - pip install -r requirements.txt

before_script:
  - psql -c "create extension postgis;" -U postgres
  - psql -c "create database public.test_db;" -U postgres
  - psql -c "create user test_user with password 'test_password';" -U postgres
  - psql -c "grant all privileges on database public.test_db to test_user;" -U postgres
  - psql -f test/test_load.sql -U postgres

script: 
  - python test/testsuite.py
  