language: python
python:
  - "2.7"
  - "3.5"
  
services:
  - postgresql
  
addons:
  postgresql: "9.1"
    
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y # For postgresql-9.1-postgis-2.1
  - sudo rm -f /etc/apt/sources.list.d/pgdg.list # postgis from pgdg requires different gdal package than the grass package
  - sudo apt-get update -qq
  - sudo apt-get remove postgresql-9.1-postgis-2.1 # Remove postgis from pgdg, will install postgis from ubuntugis-unstable instead
  
install:
  #- mkdir ldsapi
  #- git clone https://github.com/josephramsay/LDSAPI.git ldsapi
  #- python ldsapi/setup.py install
  - sudo apt-get install libgdal-dev libgdal1h
  - sudo apt-get install --no-install-recommends postgresql-9.1-postgis-2.1
  - sudo apt-get install smbclient libsmbclient-dev
  - pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install -e "git+https://github.com/josephramsay/LDSAPI#egg=LDSAPI"
  - echo $PYTHONPATH
  
before_script:
  - mv test/database.yml.travis test/database.yml
  - mv assets/config.ini.template assets/config.ini
  - psql -c "create database test_db;" -U postgres
  - psql -c "create user test_user with password 'test_password';" -U postgres
  - psql -c "grant all privileges on database test_db to test_user;" -U postgres
  - psql -d test_db -c "create extension postgis;" -U postgres
  - psql -d test_db -f test/test_load.sql -U test_user
  - psql -d test_db -f sql/nbrfnc.sql -U test_user
  - psql -d test_db -f sql/topoview.sql -U test_user
  #- psql -d test_db -c "select table_name from information_schema.tables where table_schema = 'public';" -U test_user
  #- psql -d test_db -c "select * from public.test_pt" -U test_user
  #- psql -d test_db -c "select * from public.new_test_pt" -U test_user
  #- find . -type f

script: 
  - coverage run test/testsuite.py
  
after_success:
  - coveralls

  