language: python
python:
  - "2.7"
  - "3.5"

services:
  - postgresql
  
addons:
  postgresql: "9.1"
    

before_install:
  # METHOD 3
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y # For postgresql-9.1-postgis-2.1
  - sudo ls /etc/apt/sources.list.d/
  - sudo rm -f /etc/apt/sources.list.d/pgdg-source.list # postgis from pgdg requires different gdal package than the grass package
  - sudo apt-get update -qq
  - sudo apt-get remove postgresql-9.1-postgis-2.1 # Remove postgis from pgdg, will install postgis from ubuntugis-unstable instead
  #- sudo apt-get install --no-install-recommends postgresql-9.1-postgis-2.1
  
install:
  # METHOD 2
  #- sudo rm /etc/apt/sources.list.d/ubuntugis-stable-source.list
  #- sudo apt-get update -qq
  #- sudo apt-get install -qq python-gdal gdal-bin binutils
  ##- ln -s /usr/lib/python2.7/dist-packages/osgeo ~/virtualenv/python2.7/lib/python2.7/site-packages/
  ##- ln -s /usr/lib/python2.7/dist-packages/GDAL-1.7.3.egg-info ~/virtualenv/python2.7/lib/python2.7/site-packages/
  
  # METHOD 1
  - sudo apt-get install libgdal-dev libgdal1h
  #- sudo apt-get install postgresql-9.1-postgis-2.1
  - sudo apt-get install --no-install-recommends postgresql-9.1-postgis-2.1
  - pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`
  - pip install -r requirements.txt

before_script:
  #- cp test/database.yml database.yml  
  - psql -c "create extension postgis;" -U postgres
  - psql -c "create database test_db;" -U postgres
  - psql -c "create user test_user with password 'test_password';" -U postgres
  - psql -c "grant all privileges on database test_db to test_user;" -U postgres

script: 
  - python test/testsuite.py