---

################################################################################
#
# Copyright 2013 Crown copyright (c)
# Land Information New Zealand and the New Zealand Government.
# All rights reserved
#
# This program is released under the terms of the new BSD license. See the
# LICENSE file for more information.
#
################################################################################
- name: Display proxy vars
  debug:
    var: web_proxy
### CLUSTERING
- name: Install packages
  apt:
    pkg: "{{ item }}"
    force: yes
    install_recommends: no
    state: latest
  with_items:
    - unzip
  environment: "{{ apt_proxy }}"
  become: yes

# TODO: add support for i386
- name: Download and install Serf
  unarchive:
    src: "{{ serf_url }}/serf_{{ serf_version }}_linux_amd64.zip"
    dest: /usr/local/bin
    mode: 700
    copy: no
    creates: /usr/local/bin/serf
  environment: "{{ web_proxy }}"
  become: yes


### CONFIGURATION
- name: Create Serf configuration directory
  file:
    path: /etc/serf
    state: directory
    mode: 0755
  become: yes

- name: Install Serf key
  template:
    src: serf/serf.key.j2
    dest: /etc/serf/serf.key
    mode: 0600
  notify:
    - service serf-agent restart
  become: yes
  when: SYSTEM_CLUSTER_KEY|default(False)


# cluster agent
- name: Install Serf agent service
  template:
    src: serf/init/serf-agent.conf.j2
    dest: /etc/init/serf-agent.conf
  notify:
  - service serf-agent restart
  become: yes

- name: Register Serf agent service
  file:
    src: /lib/init/upstart-job
    dest: /etc/init.d/serf-agent
    state: link
  notify:
    - service serf-agent restart
  become: yes


# cluster names
- name: Install cluster names service
  template:
    src: serf/init/cluster-names.conf.j2
    dest: /etc/init/cluster-names.conf
  notify:
    - service cluster-names restart
  become: yes

- name: Register cluster names service
  file:
    src: /lib/init/upstart-job
    dest: /etc/init.d/cluster-names
    state: link
  notify:
    - service cluster-names restart
  become: yes


### HANDLERS ROUTER
- name: Create Serf handlers directory
  file:
    path: /etc/serf/handlers
    state: directory
    mode: 0755
  become: yes

- name: Install Serf handlers router
  copy:
    src: serf/handlers.sh
    dest: /usr/local/bin/serf-handlers.sh
    mode: 0755
  become: yes


### HANDLERS
- name: Install cluster handlers
  copy:
    src: serf/member-any-change
    dest: /etc/serf/handlers/{{ item }}
    mode: 0755
  with_items:
    - member-join
    - member-update
    - member-leave
    - member-failed
  become: yes

# Manual cluster join if automatic join using mDNS multicasts wouldn't work.
# If manual approach is used, reconnection after restart must be solved.

#- name: Join cluster on SYSTEM_NETWORK_DEVICE network device
#  command: >
#    serf join {{ hostvars[item]['ansible_' + SYSTEM_NETWORK_DEVICE]['ipv4'].address }}
#    |
#    true
#  with_items: "{{ groups.all }}"
#  become: yes

# vim: set ts=2 sts=2 sw=2 et:
