---

# IMPORTANT: this role require following configuration in 'database' role:

# DB_EXTENSION_TABLE_VERSION: yes
# DB_EXTENSION_DBPATCH: yes


# BDE database name
BDE_DATABASE_NAME: linz


# Path to BDE data directory
BDE_REPOSITORY_DIR: /store/bde-processor/repository

# Path to temporary directory used for storing working files
BDE_TMP_BASE_DIR: /store/bde-processor/tmp

# Email address used for sending messages from BDE files processing
BDE_LOG_EMAIL_ADDRESS: linzdataserviceadmin@linz.govt.nz


# SQL to be run each time a dataset load is started
BDE_DATASET_LOAD_START_SQL: |
  SELECT bde_CreateDatasetRevision({{ '{{id}}' }});

# SQL to be run each time a dataset load is completed
BDE_DATASET_LOAD_END_SQL: |
  SELECT lds.LDS_MaintainSimplifiedLayers({{ '{{id}}' }});
  SELECT bde_ext.LDS_MaintainAllFBDELayers({{ '{{id}}' }});
  SELECT bde_CompleteDatasetRevision({{ '{{id}}' }});


# Cron time string specifying when daily BDE data upload will be executed.
# Format: minute hour day_of_month month day_of_week
BDE_UPLOAD_TIME_DAILY: 30 0  * * *

# Cron time string specifying when weekly BDE data upload will be executed.
# Format: minute hour day_of_month month day_of_week
BDE_UPLOAD_TIME_WEEKLY: 0 14  * * 0
