---

################################################################################
#
# Copyright 2013 Crown copyright (c)
# Land Information New Zealand and the New Zealand Government.
# All rights reserved
#
# This program is released under the terms of the new BSD license. See the
# LICENSE file for more information.
#
################################################################################

- name: Detect installed PostgreSQL version
  command: >
    psql
    -v ON_ERROR_STOP=yes
    -tAc
    "
    SELECT
    substring(current_setting('server_version') from '^[0-9]*\.[0-9]*');
    "
  become: yes
  become_user: postgres
  register: postgresql_version_d


- name: Install packages
  apt:
    pkg: "{{ item }}"
    force: yes
    install_recommends: no
    state: latest
  with_items:
    - libkrb5-dev
    - postgresql-server-dev-{{ postgresql_version_d.stdout }}
    - postgresql-{{ postgresql_version_d.stdout }}-pgtap
  environment: "{{ apt_proxy }}"
  become: yes


### VARIABLES
- name: Set PostgreSQL version variable
  set_fact:
    postgresql_version: "{{ postgresql_version_d.stdout }}"


### USER
- name: Create database user for development
  postgresql_user:
    name: "{{ ansible_user }}"
    password: "{{ ansible_user }}"
    role_attr_flags: CREATEDB,CREATEROLE,SUPERUSER
    state: present
  become: yes
  become_user: postgres


### SOURCE CODE DIRECTORY
- name: Create directory for source code
  file:
    path: /home/{{ ansible_user }}/src
    state: directory
    mode: 0755


### PROXY SETTINGS
- name: Install proxy configuration for Git
  git_config:
    name: "{{ item.protocol }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - {
        protocol: http.proxy,
        value: "{{ web_proxy.http_proxy }}"
      }
    - {
        protocol: https.proxy,
        value: "{{ web_proxy.https_proxy }}"
      }


### PLDEBUGGER
- name: Download pldebugger source code
  git:
    repo: "{{ pldebugger_repository }}"
    dest: /home/{{ ansible_user }}/src/pldebugger
    version: master
  environment: "{{ web_proxy }}"

- name: Build pldebugger
  shell: >
    USE_PGXS=1
    make
  args:
    chdir: /home/{{ ansible_user }}/src/pldebugger

- name: Install pldebugger
  shell: >
    USE_PGXS=1
    make install
  args:
    chdir: /home/{{ ansible_user }}/src/pldebugger
  become: yes


### PLPROFILER
- name: Download plprofiler source code
  git:
    repo: "{{ plprofiler_repository }}"
    dest: /home/{{ ansible_user }}/src/plprofiler
    version: master
  environment: "{{ web_proxy }}"

- name: Build plprofiler
  shell: >
    USE_PGXS=1
    make
  args:
    chdir: /home/{{ ansible_user }}/src/plprofiler

- name: Install plprofiler
  shell: >
    USE_PGXS=1
    make install
  args:
    chdir: /home/{{ ansible_user }}/src/plprofiler
  become: yes


### CONFIGURATION
- name: Activate pldebugger PostgreSQL extensions
  copy:
    content: |
      # enable plugin_debugger or plprofiler here (only one in time)
      shared_preload_libraries = '$libdir/plugin_debugger'
    dest: "{{ pgsql_config_dir }}/100-postgresql-develop.conf"
  notify:
    - service postgresql restart
  become: yes


- meta: flush_handlers

# vim: set ts=2 sts=2 sw=2 et:
