---

################################################################################
#
# Copyright 2013 Crown copyright (c)
# Land Information New Zealand and the New Zealand Government.
# All rights reserved
#
# This program is released under the terms of the new BSD license. See the
# LICENSE file for more information.
#
################################################################################

- name: service postgresql restart
  service:
    name: postgresql
    state: restarted
  become: yes

- name: sysctl postgresql reload
  command: sysctl --load /etc/sysctl.d/90-postgresql-tune.conf
  become: yes

- name: service nagios-nrpe-server restart
  service:
    name: nagios-nrpe-server
    state: restarted
  become: yes

# vim: set ts=2 sts=2 sw=2 et:
