#!/bin/bash

################################################################################
#
# Wrapper script to run the linz_bde_uploader.
#
# Copyright 2011 Crown copyright (c)
# Land Information New Zealand and the New Zealand Government.
# All rights reserved
#
# This program is released under the terms of the new BSD license. See the
# LICENSE file for more information.
#
################################################################################

# TODO: rotate log file


set -e

DATABASE=$1
CONFIG=$2

LOGDIR=/var/log/linz-bde-uploader
BDE_USER=bde


usage() {
    echo "
USAGE: bde_upload DATABASE CONFIG [OPTS]

OPTIONS:
  DATABASE: name of target database
  CONFIG  : absolute path to BDE uploader configuration files without
            extension.
            Two configuration files must exist. See CONFIGURATION
            section
  OPTS    : optional linz_bde_uploader options passed to bde_upload

CONFIGURATION:
  CONFIG.conf:
            linz_bde_uploader configuration file containing default values
  CONFIG.conf.DATABASE:
            linz_bde_uploader configuration file containing custom
            configuration
"
    exit 1
}


cleanup() {
    echo -e "\nRunning cleanup ..."
    # currently, there is no cleanup task implemented
}


### SANITY CHECKS
if [ "$(id -un)" != "$BDE_USER" ]; then
    echo "Must be executed as 'bde' user"
    usage
fi

if [ -z "$DATABASE" ]; then
    echo "Missing database name"
    usage
fi

if [ ! -f "$CONFIG.conf" ]; then
    echo "Missing default BDE uploader configuration file ($CONFIG.conf)"
    usage
fi

if [ ! -f "$CONFIG.conf.$DATABASE" ]; then
    echo "Missing custom BDE uploader configuration file ($CONFIG.conf.$DATABASE)"
    usage
fi

if [ $(ps -ef | grep -c "/usr/bin/linz_bde_uploader") -gt 1 ]; then
    echo "Another instance of 'linz_bde_uploader' is already running"
    exit 1
fi


# DATA REPOSITORY
trap cleanup ERR EXIT


# UPLOAD
# detect if database contains level 0 upload
LEVEL_0=$( \
    psql -d $DATABASE \
    -tAc \
    " \
    SELECT COUNT(*) \
    FROM bde_control.upload \
    WHERE status = 'C' \
    " \
)


# perform upload
if [ "$LEVEL_0" == "0" ]; then
    echo -e "\nRunning LEVEL 0 upload ..."
    linz_bde_uploader \
        -full \
        -config-path $CONFIG.conf \
        -config-extension $DATABASE \
        -listing $LOGDIR/linz_bde_uploader.log \
        -log-level INFO \
        -remove-zombie \
        "${@:3}"

    # enable versioning (must be executed with superuser permissions)
    sudo -u postgres \
    psql \
        -d $DATABASE \
        -f /usr/share/linz-bde-schema/sql/versioning/01-version_tables.sql

    sudo -u postgres \
    psql \
        -d $DATABASE \
        -f /usr/share/linz-lds-bde-schema/sql/versioning/01-version_tables.sql

else
    echo -e "\nRunning LEVEL 5 upload ..."
    linz_bde_uploader \
        -full-incremental \
        -incremental \
        -config-path $CONFIG.conf \
        -config-extension $DATABASE \
        -listing $LOGDIR/linz_bde_uploader.log \
        -log-level INFO \
        -remove-zombie \
        "${@:3}"
fi

# vim: set ts=4 sts=4 sw=4 et:
