#!/bin/bash

################################################################################
#
# Install development version of liblinz-utils-perl from source code.
# Script must be executed from source code root directory.
#
# Copyright 2013 Crown copyright (c)
# Land Information New Zealand and the New Zealand Government.
# All rights reserved
#
# This program is released under the terms of the new BSD license. See the
# LICENSE file for more information.
#
################################################################################


set -e

PKGNAME=liblinz-utils-perl
APPDIR=$HOME/apps


### SANITY CHECKS
if [ ! -f "Build.PL" ]; then
    echo -e "\nMust be executed from '$PKGNAME' source code root directory"
    exit 1
fi


### DEPLOYMENT
# install development version
echo -e "\nInstalling from source code to '$APPDIR' ..."
mkdir -p $APPDIR

perl Build.PL \
    --prefix=$APPDIR
./Build install


# final message
echo -e "\nDone !"

# vim: set ts=4 sts=4 sw=4 et:

