---

### LINZ Software Repository
# fingerprint: 8106 28B8 BB56 E36D 54EF  8BEF CA3D 31F0 C484 D45F
linz_repository_key_id: C484D45F

linz_repository_key: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    Version: SKS 1.1.5
    Comment: Hostname: keyserver.ubuntu.com

    mQINBFcP+38BEADcUy6HdHv8fkWQwpoqrMLBGfslI7Cai4C3z9gUO3Ixnw+IUv152xVx6kJa
    fGJrZo27D0L00Gr3clsiBX5kLudsyXCo0YHcRCG0AQr6BnIdpg4BzkIaBuFx2axgTqI1YJxl
    u5AW3FWmEpHwv1ljbTHjH4jcOSvsSCzAWCRl0VVdtMZjl8ytl2+zG9K9Xospszaemx//XJTQ
    sVbMmDMrtgaN3XxAWb06CFCFvPUlMx1myLmVga52A8CjNWhOfs4qJYQ3WtMqZbrq+sIiLFXB
    nUWn3KdYyChBwMYWLiUmBagkOwnt3RuanenQmsCXri8lUed0+R2sJJ8Ns+B2wHbTtbIR+659
    4Q65qRg9jkB4OcQ8gyPEH+6T5e6HlF1GL+nHMCxKpkfXxjMLS88i9N0X1UERvylmUUkDKDb2
    DLRD+pjp/KaqPIUvqYsJWkz2pKJ56GoI0QwpfJVpUe3G5st6Bdla0WiiMe7tqWgGgorPAuqi
    87ZkW9SWk/7/09/So80piCW9nGP4Kfqlmahs0CLTBCWAX7qIRTkTgdeGpmBXi7N7b/Af+RhN
    TVndIQI/xNj9cxYiRlCZxOr/VbJKF6Oj/ZS6J6lfvjR8sxOLl6CO6cqzJfYokzhNRvJXUW9W
    do21dOW4W6dw/ZgWeqPM/mNASJwR1NZS12XjljQ8DQahijiiUwARAQABtBZMYXVuY2hwYWQg
    UFBBIGZvciBMSU5aiQI4BBMBAgAiBQJXD/t/AhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIX
    gAAKCRDKPTHwxITUXyJGEADKsdrjUVFHkDk7xZPhiO5aC6yJZ4fciwhoaPCFWSyf8SgZ/wOT
    0HD9jTq4vaH7v7fLTCbFUTjvjzr5g2kVqz0L7VA7hgJBHZg0d8yxYku+A5xQN8yprWj58n6I
    FmGv0oRNprWCtz3zlOEGW7hBwjiVjTUCSHRj5RaLqbaS0UJB76ZFB3Eh1ilF+HWBqRVtYtvg
    jxAe/rkNt5urJq/SglCFrNWEuIjO1sRAx0nSIgu2e5jbYpRxBkS5Ho0ES8aNta/3RlZaeJR9
    Bdr1ltjukp3MhMa67UxzGUnfYVFqAex6muGhlZhp4/oKEBBzwspdVr3gncFpmNYAod4AJ92j
    d3OahFqrMfeupeW2Fn1BDPwCIP2ctS3J4v9JDbvVEolhA6D1xDlKblMAYWcK/9qb1qyvYfGT
    nEA0iW2fsnpkVoGMEsWsFwRyU38Sg6h3PSk5IwRwotu0nPyVmd7ueEZIniGLMcLDzmRKQZNN
    LsTty38zsUPQ9rG8uJ5w1gLgGN8wfnVKiszSgci7MZ7+/0TiE1MoS4pKcSxr55boBlph3Qyk
    qlCN6NW9VjZOltS/nqS5occcBPzU+8fXYIjgLsLBWUy5G02G6MbcKgTHaW5Dtnu96MLrzcek
    GRIUl6VsTqvmKUNBRaqvsr/fY7BDoEqRCj9BPlJWpVd9hRzhUSYdFvzdiA==
    =8vwn
    -----END PGP PUBLIC KEY BLOCK-----

linz_repository: deb https://{{ linz_repository_username }}:{{ linz_repository_password }}@private-ppa.launchpad.net/linz/prod/ubuntu {{ ansible_distribution_release }} main


### PostgreSQL repository (apt.postgresql.org)
pgdg_repository_key_id: ACCC4CF8

pgdg_repository_key: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    Version: GnuPG v1

    mQINBE6XR8IBEACVdDKT2HEH1IyHzXkb4nIWAY7echjRxo7MTcj4vbXAyBKOfjja
    UrBEJWHN6fjKJXOYWXHLIYg0hOGeW9qcSiaa1/rYIbOzjfGfhE4x0Y+NJHS1db0V
    G6GUj3qXaeyqIJGS2z7m0Thy4Lgr/LpZlZ78Nf1fliSzBlMo1sV7PpP/7zUO+aA4
    bKa8Rio3weMXQOZgclzgeSdqtwKnyKTQdXY5MkH1QXyFIk1nTfWwyqpJjHlgtwMi
    c2cxjqG5nnV9rIYlTTjYG6RBglq0SmzF/raBnF4Lwjxq4qRqvRllBXdFu5+2pMfC
    IZ10HPRdqDCTN60DUix+BTzBUT30NzaLhZbOMT5RvQtvTVgWpeIn20i2NrPWNCUh
    hj490dKDLpK/v+A5/i8zPvN4c6MkDHi1FZfaoz3863dylUBR3Ip26oM0hHXf4/2U
    A/oA4pCl2W0hc4aNtozjKHkVjRx5Q8/hVYu+39csFWxo6YSB/KgIEw+0W8DiTII3
    RQj/OlD68ZDmGLyQPiJvaEtY9fDrcSpI0Esm0i4sjkNbuuh0Cvwwwqo5EF1zfkVj
    Tqz2REYQGMJGc5LUbIpk5sMHo1HWV038TWxlDRwtOdzw08zQA6BeWe9FOokRPeR2
    AqhyaJJwOZJodKZ76S+LDwFkTLzEKnYPCzkoRwLrEdNt1M7wQBThnC5z6wARAQAB
    tBxQb3N0Z3JlU1FMIERlYmlhbiBSZXBvc2l0b3J5iQI9BBMBCAAnAhsDBQsJCAcD
    BRUKCQgLBRYCAwEAAh4BAheABQJS6RUZBQkOhCctAAoJEH/MfUaszEz4zmQP/2ad
    HtuaXL5Xu3C3NGLha/aQb9iSJC8z5vN55HMCpsWlmslCBuEr+qR+oZvPkvwh0Io/
    8hQl/qN54DMNifRwVL2n2eG52yNERie9BrAMK2kNFZZCH4OxlMN0876BmDuNq2U6
    7vUtCv+pxT+g9R1LvlPgLCTjS3m+qMqUICJ310BMT2cpYlJx3YqXouFkdWBVurI0
    pGU/+QtydcJALz5eZbzlbYSPWbOm2ZSS2cLrCsVNFDOAbYLtUn955yXB5s4rIscE
    vTzBxPgID1iBknnPzdu2tCpk07yJleiupxI1yXstCtvhGCbiAbGFDaKzhgcAxSIX
    0ZPahpaYLdCkcoLlfgD+ar4K8veSK2LazrhO99O0onRG0p7zuXszXphO4E/WdbTO
    yDD35qCqYeAX6TaB+2l4kIdVqPgoXT/doWVLUK2NjZtd3JpMWI0OGYDFn2DAvgwP
    xqKEoGTOYuoWKssnwLlA/ZMETegak27gFAKfoQlmHjeA/PLC2KRYd6Wg2DSifhn+
    2MouoE4XFfeekVBQx98rOQ5NLwy/TYlsHXm1n0RW86ETN3chj/PPWjsi80t5oepx
    82azRoVu95LJUkHpPLYyqwfueoVzp2+B2hJU2Rg7w+cJq64TfeJG8hrc93MnSKIb
    zTvXfdPtvYdHhhA2LYu4+5mh5ASlAMJXD7zIOZt2iEYEEBEIAAYFAk6XSO4ACgkQ
    xa93SlhRC1qmjwCg9U7U+XN7Gc/dhY/eymJqmzUGT/gAn0guvoX75Y+BsZlI6dWn
    qaFU6N8HiQIcBBABCAAGBQJOl0kLAAoJEExaa6sS0qeuBfEP/3AnLrcKx+dFKERX
    o4NBCGWr+i1CnowupKS3rm2xLbmiB969szG5TxnOIvnjECqPz6skK3HkV3jTZaju
    v3sR6M2ItpnrncWuiLnYcCSDp9TEMpCWzTEgtrBlKdVuTNTeRGILeIcvqoZX5w+u
    i0eBvvbeRbHEyUsvOEnYjrqoAjqUJj5FUZtR1+V9fnZp8zDgpOSxx0LomnFdKnhj
    uyXAQlRCA6/roVNR9ruRjxTR5ubteZ9ubTsVYr2/eMYOjQ46LhAgR+3Alblu/WHB
    MR/9F9//RuOa43R5Sjx9TiFCYol+Ozk8XRt3QGweEH51YkSYY3oRbHBb2Fkql6N6
    YFqlLBL7/aiWnNmRDEs/cdpo9HpFsbjOv4RlsSXQfvvfOayHpT5nO1UQFzoyMVpJ
    615zwmQDJT5Qy7uvr2eQYRV9AXt8t/H+xjQsRZCc5YVmeAo91qIzI/tA2gtXik49
    6yeziZbfUvcZzuzjjxFExss4DSAwMgorvBeIbiz2k2qXukbqcTjB2XqAlZasd6Ll
    nLXpQdqDV3McYkP/MvttWh3w+J/woiBcA7yEI5e3YJk97uS6+ssbqLEd0CcdT+qz
    +Waw0z/ZIU99Lfh2Qm77OT6vr//Zulw5ovjZVO2boRIcve7S97gQ4KC+G/+QaRS+
    VPZ67j5UMxqtT/Y4+NHcQGgwF/1iiQI9BBMBCAAnAhsDBQsJCAcDBRUKCQgLBRYC
    AwEAAh4BAheABQJQeSssBQkDwxbfAAoJEH/MfUaszEz4bgkP/0AI0UgDgkNNqplA
    IpE/pkwem2jgGpJGKurh2xDu6j2ZL+BPzPhzyCeMHZwTXkkI373TXGQQP8dIa+RD
    HAZ3iijw4+ISdKWpziEUJjUk04UMPTlN+dYJt2EHLQDD0VLtX0yQC/wLmVEH/REp
    oclbVjZR/+ehwX2IxOIlXmkZJDSycl975FnSUjMAvyzty8P9DN0fIrQ7Ju+BfMOM
    TnUkOdp0kRUYez7pxbURJfkM0NxAP1geACI91aISBpFg3zxQs1d3MmUIhJ4wHvYB
    uaR7Fx1FkLAxWddre/OCYJBsjucE9uqc04rgKVjN5P/VfqNxyUoB+YZ+8Lk4t03p
    RBcD9XzcyOYlFLWXbcWxTn1jJ2QMqRIWi5lzZIOMw5B+OK9LLPX0dAwIFGr9WtuV
    J2zp+D4CBEMtn4Byh8EaQsttHeqAkpZoMlrEeNBDz2L7RquPQNmiuom15nb7xU/k
    7PGfqtkpBaaGBV9tJkdp7BdH27dZXx+uT+uHbpMXkRrXliHjWpAw+NGwADh/Pjmq
    ExlQSdgAiXy1TTOdzxKH7WrwMFGDK0fddKr8GH3f+Oq4eOoNRa6/UhTCmBPbryCS
    IA7EAd0Aae9YaLlOB+eTORg/F1EWLPm34kKSRtae3gfHuY2cdUmoDVnOF8C9hc0P
    bL65G4NWPt+fW7lIj+0+kF19s2PviQI9BBMBCAAnAhsDBQsJCAcDBRUKCQgLBRYC
    AwEAAh4BAheABQJRKm2VBQkINsBBAAoJEH/MfUaszEz4RTEP/1sQHyjHaUiAPaCA
    v8jw/3SaWP/g8qLjpY6ROjLnDMvwKwRAoxUwcIv4/TWDOMpwJN+CJIbjXsXNYvf9
    OX+UTOvq4iwi4ADrAAw2xw+Jomc6EsYla+hkN2FzGzhpXfZFfUsuphjY3FKL+4hX
    H+R8ucNwIz3yrkfc17MMn8yFNWFzm4omU9/JeeaafwUoLxlULL2zY7H3+QmxCl0u
    6t8VvlszdEFhemLHzVYRY0Ro/ISrR78CnANNsMIy3i11U5uvdeWVCoWV1BXNLzOD
    4+BIDbMB/Do8PQCWiliSGZi8lvmj/sKbumMFQonMQWOfQswTtqTyQ3yhUM1LaxK5
    PYq13rggi3rA8oq8SYb/KNCQL5pzACji4TRVK0kNpvtxJxe84X8+9IB1vhBvF/Ji
    /xDd/3VDNPY+k1a47cON0S8Qc8DA3mq4hRfcgvuWy7ZxoMY7AfSJOhleb9+PzRBB
    n9agYgMxZg1RUWZazQ5KuoJqbxpwOYVFja/stItNS4xsmi0lh2I4MNlBEDqnFLUx
    SvTDc22c3uJlWhzBM/f2jH19uUeqm4jaggob3iJvJmK+Q7Ns3WcfhuWwCnc1+58d
    iFAMRUCRBPeFS0qd56QGk1r97B6+3UfLUslCfaaA8IMOFvQSHJwDO87xWGyxeRTY
    IIP9up4xwgje9LB7fMxsSkCDTHOk
    =s3DI
    -----END PGP PUBLIC KEY BLOCK-----

pgdg_repository: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main


serf_version: 0.7.0
serf_url: http://gislab-software.s3.amazonaws.com
